# .github/workflows/merge.yml
name: Merge Validate

on:
  pull_request:
    branches: [stage, master] # или другая целевая ветка

jobs:
  test:
    name: Merge Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test
